- hosts: localhost
  become: true
  tasks:
  - name: Install curl
    apt: name=curl
  - name: Install zsh
    apt: name=zsh 
  - name: Install antibody
    shell: curl -sfL git.io/antibody | sh -s - -b /usr/local/bin 
  - name: Install tmux
    apt: name=tmux
  - name: Install neovim
    apt: name=neovim
  - name: Install stow
    apt: name=stow
  - name: Install bat
    apt: name=bat
  - name: Install dracula vim theme
    ansible.builtin.git:
      repo: https://github.com/dracula/vim.git 
      dest: ./vim/.vim/pack/themes/opt/dracula
      update: true
  - name: Install vim fugitive plugin
    ansible.builtin.git:
      repo: https://github.com/tpope/vim-fugitive.git 
      dest: ./vim/.vim/pack/git/start/fugitive 
      update: true
  - name: Install ctrlp plugin
    ansible.builtin.git:
      repo: https://github.com/ctrlpvim/ctrlp.vim.git
      dest: ./vim/.vim/pack/general/start/ctrlp
      update: true
  - name: Install vim-easymotion plugin
    ansible.builtin.git:
      repo: https://github.com/easymotion/vim-easymotion.git 
      dest: ./vim/.vim/pack/general/start/vim-easymotion
      update: true
  - name: Install plug for neovim
    shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  - name: Stow git
    shell: stow git
  - name: Stow zsh
    shell: stow zsh
  - name: Stow vim
    shell: stow vim
  - name: Stow nvim
    shell: stow nvim
  - name: Configure zsh to shells
    shell: command -v zsh | sudo tee -a /etc/shells
  - name: Change shell to zsh
    shell: chsh -s $(which zsh) $USER
  - name: Install zsh_plugins
    shell: antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
