- hosts: localhost
  become: true
  tasks:
  - name: Install nix
    shell: curl -L https://nixos.org/nix/install | sh
  - name: Add permissions for nix
    shell: chmod +x ~/.nix-profile/etc/profile.d/nix.sh
  - name: Source nix
    shell: . ~/.nix-profile/etc/profile.d/nix.sh
  - name: Install zsh
    shell: nix-env -iA nixpkgs.zsh
  - name: Install antibody
    shell: nix-env -iA nixpkgs.antibody
  - name: Install tmux
    shell: nix-env -iA nixpkgs.tmux
  - name: Install neovim
    shell: nix-env -iA nixpkgs.neovim
  - name: Install stow
    shell: nix-env -iA nixpkgs.stow
  - name: Install bat
    shell: nix-env -iA nixpkgs.bat
  - name: Install dracula vim theme
    ansible.builtin.git:
      repo: https://github.com/dracula/vim.git 
      dest: ./vim/.vim/pack/themes/opt/dracula
      update: true
  - name: Install vim fugitive plugin
    ansible.builtin.git:
      repo: https://github.com/tpope/vim-fugitive.git 
      dest: ./vim/.vim/pack/git/start/fugitive 
      update: true
  - name: Install ctrlp plugin
    ansible.builtin.git:
      repo: https://github.com/ctrlpvim/ctrlp.vim.git
      dest: ./vim/.vim/pack/general/start/ctrlp
      update: true
  - name: Install vim-easymotion plugin
    ansible.builtin.git:
      repo: https://github.com/easymotion/vim-easymotion.git 
      dest: ./vim/.vim/pack/general/start/vim-easymotion
      update: true
  - name: Install packer neovim plugin
    ansible.builtin.git:
      repo: https://github.com/wbthomason/packer.nvim
      dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      update: true
      depth: 1
  - name: Stow git
    shell: stow git
  - name: Stow zsh
    shell: stow zsh
  - name: Stow vim
    shell: stow vim
  - name: Stow nvim
    shell: stow nvim
  - name: Configure zsh to shells
    shell: command -v zsh | sudo tee -a /etc/shells
  - name: Change shell to zsh
    shell: sudo chsh -s $(which zsh) $USER
  - name: Install neovim plugins
    shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  - name: Install zsh_plugins
    shell: antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
