- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  vars:
    source_key: "./ssh/.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_pub_key: "./ssh/.ssh/id_ed25519.pub"
    dest_pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  tasks:
  - name: Ensure .ssh directory exists.
    become_user: root
    file:
      dest: "{{ dest_key | dirname }}"
      mode: 0700
      state: directory
    tags:
      - dotfiles
      - ssh
  - name: Install ssh key
    become_user: root
    copy:
      src: "{{ source_key }}"
      dest: "{{ dest_key }}"
      mode: 0600
    tags:
      - dotfiles
      - ssh
  - name: Install ssh pub key
    become_user: root
    copy:
      src: "{{ source_pub_key }}"
      dest: "{{ dest_pub_key }}"
      mode: 0600
    tags:
      - dotfiles
      - ssh
  - name: Give ownership of .ssh to user
    become_user: "{{ lookup('env', 'USER') }}"
    shell: chown -R {{ lookup('env', 'USER') }}:{{ lookup('env', 'USER') }} /home/{{ lookup('env', 'USER') }}/.ssh
  - name: Install curl
    apt: name=curl
    tags:
      - dotfiles
      - zsh
      - neovim
  - name: Install fzf
    apt: name=fzf
    tags:
      - dotfiles
      - tmux
  - name: Install zsh
    apt: name=zsh 
    tags:
      - zsh
  - name: Install antibody
    shell: curl -sfL git.io/antibody|sh -s - -b /usr/local/bin 
    tags:
      - zsh
  - name: Install git 
    apt: name=git
    tags:
      - git
  - name: Install neovim
    include_tasks:
      file: tasks/neovim-install.yml
      apply:
        tags:
          - neovim
  - name: Install tar
    apt: name=tar
    tags:
      - lazygit
  - name: Install lazygit
    shell: |
      LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[0-35.]+')
      curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
      tar xf lazygit.tar.gz -C /usr/local/bin lazygit
      rm lazygit.tar.gz
    tags:
      - lazygit
  - name: Install tmux
    apt: name=tmux
    tags:
      - tmux
  - name: Install neovim
    apt: name=neovim
    tags:
      - neovim
  - name: Install unzip
    apt: name=unzip
    tags:
      - neovim
  - name: Install node
    apt: name=nodejs
    tags:
      - node
  - name: Install npm
    apt: name=npm
    tags:
      - node
  - name: Install n
    npm:
      name: n
      global: true
    tags:
      - node
  - name: Node 16
    shell: n 16
    tags:
      - node
  - name: Install tldr
    npm:
      name: tldr
      global: true
  - name: Install prettier
    npm:
      name: prettier
      global: true
  - name: Install eslint
    npm:
      name: eslint
      global: true
  - name: Install stow
    apt: name=stow
    tags:
      - dotfiles
      - stow
  - name: Install bat
    apt: name=bat
    tags:
      - bat
  - name: Install packer neovim plugin
    git:
      repo: https://github.com/wbthomason/packer.nvim
      dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      update: true
      depth: 1
    tags:
      - neovim
  - name: Stow git
    shell: stow git
    tags:
      - dotfiles
  - name: Stow zsh
    shell: stow zsh
    tags:
      - dotfiles
  - name: Stow nvim
    shell: stow nvim
    tags:
      - dotfiles
  - name: Stow tmux
    shell: stow tmux
    tags:
      - dotfiles
  - name: Set authorized key took from file
    authorized_key:
      user: "{{ lookup('env', 'USER') }}"
      state: present
      key: "{{ lookup('file', item) }}"
    with_fileglob:
      - ./ssh/.ssh/id_ed25519.pub
    tags:
      - dotfiles
      - ssh
  - name: Configure zsh to shells
    shell: command -v zsh | tee -a /etc/shells
    tags: 
      - zsh
  - name: Change shell to zsh
    shell: "chsh -s $(which zsh) {{ lookup('env', 'USER') }}" 
    tags: 
      - zsh
  - name: Install zsh_plugins
    become: false
    become_user: "{{ lookup('env', 'USER') }}"
    shell: "antibody bundle < /home/{{ lookup('env', 'USER') }}/.zsh_plugins.txt > /home/{{ lookup('env', 'USER') }}/.zsh_plugins.sh"
    tags: 
      - zsh
  - name: Give ownership of .dotfiles to user
    shell: chown -R {{ lookup('env', 'USER') }}:{{ lookup('env', 'USER') }} /home/{{ lookup('env', 'USER') }}/.dotfiles
  - name: Install neovim clipboard support for wsl
    shell: |
      curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
      unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
      chmod +x /tmp/win32yank.exe
      mv /tmp/win32yank.exe /usr/local/bin/
