- name: Install docker
  pacman: name=docker
  tags:
    - work
- name: Install docker-compose
  pacman: name=docker-compose
  tags:
    - work
- name: Start docker
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: sudo systemctl start docker
  tags:
    - work
    - gui
- name: Start docker
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: sudo systemctl enable docker
  tags:
    - work
    - gui
- name: Stop all docker containers
  shell: docker stop $(docker ps -a -q)
- name: Remove all docker containers
  shell: docker rm $(docker ps -a -q)
- name: Add user to new group
  shell: usermod -aG docker {{ lookup('env', 'USER') }}
  tags:
    - work
- name: Install and run redis
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: sudo docker run --name redis -p 6379:6379 -d redis
  tags:
    - work
- name: Install and run azurite
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: sudo docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite
  tags:
    - gui
    - work
- name: Install dotnet-host-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-host-bin
  tags:
    - work
- name: Install dotnet-runtime-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-runtime-bin
  tags:
    - work
- name: Install dotnet-sdk-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-sdk-bin
  tags:
    - work
- name: Install dotnet-targeting-pack-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-targeting-pack-bin
  tags:
    - work
- name: Install aspnet-runtime-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm aspnet-runtime-bin
  tags:
    - work
- name: Install aspnet-targeting-pack-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm aspnet-targeting-pack-bin
  tags:
    - work
- name: Install aspnet-runtime-5.0-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm aspnet-runtime-5.0-bin
  tags:
    - work
- name: Install aspnet-targeting-pack-5.0-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm aspnet-targeting-pack-5.0-bin
  tags:
    - work
- name: Install dotnet-runtime-bin-5.0-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-runtime-5.0-bin
  tags:
    - work
- name: Install dotnet-sdk-5.0-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-sdk-5.0-bin
  tags:
    - work
- name: Install dotnet-targeting-pack-5.0-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm dotnet-targeting-pack-5.0-bin
  tags:
    - work
- name: Install Azure Data Studio
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm azuredatastudio-bin
  tags:
    - work
    - gui
- name: Install rider
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm rider
  tags:
    - work
    - gui
- name: Install powershell-bin
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: yay -S --noconfirm powershell-bin
  tags:
    - work
- name: Download artifacts provider
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)"
  tags:
    - work
- name: Download dotnet-ef
  become_user: "{{ lookup('env', 'USER') }}"
  become: false
  shell: dotnet-ef || dotnet tool install --global dotnet-ef
  tags:
    - work
- name: Create source directory
  shell: |
    mkdir -p /home/{{ lookup('env', 'USER') }}/source
    chown -R {{ lookup('env', 'USER') }}:wheel /home/{{ lookup('env', 'USER') }}/
  tags:
    - work
- name: Add underwriting project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/underwriting" ] ; then
        git clone git@github.com:Nude-Solutions/underwriting.git /home/{{ lookup('env', 'USER') }}/source/underwriting
    fi
  tags:
    - work
- name: Copy over underwriting config
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: cp -f /home/{{ lookup('env', 'USER') }}/.dotfiles/project-config/underwriting/appsettings.local.json /home/{{ lookup('env', 'USER') }}/source/underwriting/server/Presentation/appsettings.local.json
  tags:
    - work
- name: Add party project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/party" ] ; then
        git clone git@github.com:Nude-Solutions/party.git /home/{{ lookup('env', 'USER') }}/source/party
    fi
  tags:
    - work
- name: Copy over party config
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: cp -f /home/{{ lookup('env', 'USER') }}/.dotfiles/project-config/party/appsettings.local.json /home/{{ lookup('env', 'USER') }}/source/party/server/Presentation/appsettings.local.json
  tags:
    - work
- name: Add search project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/search" ] ; then
        git clone git@github.com:Nude-Solutions/search.git /home/{{ lookup('env', 'USER') }}/source/search
    fi
  tags:
    - work
- name: Add finance project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/finance" ] ; then
        git clone git@github.com:Nude-Solutions/finance.git /home/{{ lookup('env', 'USER') }}/source/finance
    fi
  tags:
    - work
- name: Add admin project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/admin" ] ; then
        git clone git@github.com:Nude-Solutions/admin.git /home/{{ lookup('env', 'USER') }}/source/admin
    fi
  tags:
    - work
- name: Add activity project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/activity" ] ; then
        git clone git@github.com:Nude-Solutions/activity.git /home/{{ lookup('env', 'USER') }}/source/activity
    fi
  tags:
    - work
- name: Add integration project
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/Integration" ] ; then
        git clone git@github.com:Nude-Solutions/integration.git /home/{{ lookup('env', 'USER') }}/source/Integration
    fi
  tags:
    - work
- name: Add base-components
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/base-components" ] ; then
        git clone git@github.com:Nude-Solutions/base-components.git /home/{{ lookup('env', 'USER') }}/source/base-components
    fi
  tags:
    - work
- name: Add base-functionality
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/base-functionality" ] ; then
        git clone git@github.com:Nude-Solutions/base-functionality.git /home/{{ lookup('env', 'USER') }}/source/base-functionality
    fi
  tags:
    - work
- name: Add connex-front-end
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  shell: |
    if [ ! -d "/home/{{ lookup('env', 'USER') }}/source/connex-front-end" ] ; then
        git clone git@github.com:Nude-Solutions/connex-front-end.git /home/{{ lookup('env', 'USER') }}/source/connex-front-end
    fi
  tags:
    - work
