local options = {
	number = true,
	relativenumber = true,
	signcolumn = "auto",
	swapfile = false,
	backup = false,
	hlsearch = false,
	ignorecase = true,
	history = 1000,
	ruler = true,
	showcmd = true,
	wildmenu = true,
	scrolloff = 8,
	incsearch = true,
	expandtab = true,
	wrap = false,
	shiftwidth = 4,
	tabstop = 4,
	softtabstop = 4,
	hidden = true,
	autoindent = true,
	smartindent = true,
	updatetime = 50,
	fileencoding = "UTF-8",
	undodir = os.getenv("HOME") .. "/.vim/undodir",
	--    clipboard = "unnamedplus",
	cmdheight = 2,
	conceallevel = 0,
	cursorline = true,
	showtabline = 2,
	splitbelow = true,
	splitright = true,
	completeopt = { "menuone", "noselect" },
	timeoutlen = 1000,
	undofile = true,
	numberwidth = 2,
	guifont = "monospace:h17",
	guicursor = "",
	termguicolors = true,
	autoread = true,
}
-- set all options
for k, v in pairs(options) do
	vim.opt[k] = v
end
